# These are supported funding model platforms

github: [tamojit-123]
patreon: tamojit
open_collective: # Replace with a single Open Collective username
ko_fi: tamojit
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://iobriefs.netlify.app/
